precision: '32'
run_name: convnext_transformerhead_pre-trained_lr0.0001
log_every_n_steps: 10
accelerator: 'gpu'
devices: 1
max_epochs: 30
batch_size: 32
data_dir: /scratch/izar/ishii
tasks:
  - pathmnist
  - dermamnist
  - breastmnist
  - tissuemnist
  - organcmnist
iter_mode: max_size
encoder_type: convnext_tiny
head: MultiheadAttention
pretrained: True
lr: 0.0001