precision: '32'
run_name: convnext_tiny_mha_pre-trained_clip_embedding_8_datasets
log_every_n_steps: 10
accelerator: 'gpu'
devices: 1
max_epochs: 30
batch_size: 16
data_dir: /scratch/izar/ishii
tasks:
  - pathmnist
  - dermamnist
  - breastmnist
  - tissuemnist
  - organcmnist
  - organsmnist
  - bloodmnist
  - octmnist
iter_mode: max_size
encoder_type: convnext_tiny
head: MultiheadAttention
pretrained: True
lr: 0.0001
#wandb_checkpoint: takuya5115/MedMNIST_lightning/model-hoix6ar1:latest
combine_clip_embedding: True
