precision: '32'
run_name: resnet18_baseline_non-trained
log_every_n_steps: 10
accelerator: 'gpu'
devices: 1
max_epochs: 30
batch_size: 32
data_dir: /scratch/izar/ishii
tasks:
  - pathmnist
  - dermamnist
  - breastmnist
  - tissuemnist
  - organcmnist
iter_mode: max_size
encoder_type: resnet18
pretrained:  False
lr: 0.001
